// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtOUSVkS-bHtsKQ9yalwxpglJ7Z3CU228',
    appId: '1:28681688070:web:a172b872cd1c50bec69f87',
    messagingSenderId: '28681688070',
    projectId: 'tawasol-social-app',
    authDomain: 'tawasol-social-app.firebaseapp.com',
    storageBucket: 'tawasol-social-app.appspot.com',
    measurementId: 'G-RCWXMKNEY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDe1S82CKLaqnUVkomvK4nG0_PDHotDM0',
    appId: '1:28681688070:android:270260f1d5dc9ef9c69f87',
    messagingSenderId: '28681688070',
    projectId: 'tawasol-social-app',
    storageBucket: 'tawasol-social-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_S6a4gsb3BmeDvwMTHvR8NR5BUruRtLg',
    appId: '1:28681688070:ios:2b9be79e76fdddc6c69f87',
    messagingSenderId: '28681688070',
    projectId: 'tawasol-social-app',
    storageBucket: 'tawasol-social-app.appspot.com',
    iosBundleId: 'com.amr.templet',
  );
}
